#GET
GET http://localhost:8080/

#GET-Users
GET http://localhost:8080/users/

#GET
GET http://localhost:8080/hello/david

#POST
POST http://localhost:8080/
content-type: application/json

{
    "nombre": "david",
    "apellido": "silva"
}