#(?id)= ingresar id manual
###Users
#GET
GET http://localhost:8000/users

#POST
POST http://localhost:8000/users
content-type: application/json
{
    "firstname": "ffffcsdsd",
    "lastname": "xtuki",
    "passporttype": "DNI",
    "passportnumber": "434",
    "email": "david@gmail.com",
    "password": "iksdi",
    "personalcard": {
        "card": "Visa",
        "cardnumber": "2323",
        "csc": "2232323",
        "total": 2332,
        "expirationdate": "23/21/1923"
    }
}

#PUT
PUT http://localhost:8000/users/(?id)
content-type: application/json
{
    "firstname": "ffffcsdsd",
    "lastname": "xtuki",
    "passporttype": "DNI",
    "passportnumber": "434",
    "email": "david@gmail.com",
    "password": "iksdi",
    "personalcard": {
        "card": "Visa",
        "cardnumber": "2323",
        "csc": "2232323",
        "total": 2332,
        "expirationdate": "23/21/1923"
    }
}

#Delete
DELETE http://localhost:8000/users/(?id)

###Flights
#GET
GET http://localhost:8000/flights

#POST
POST http://localhost:8000/flights
content-type: application/json
{
	"AirplaneModel": "sadasdusho",
	"AirplaneNumber": "2213",
	"Price": 32432,
	"Depart": {
		"Country": "peru",
		"City": "Lima",
		"TD": "12:20",
		"TA": "22:20"
	},
	"Destin": {
		"Country": "Colombia",
		"City": "Cali",
		"TD": "11:20",
		"TA": "21:20"
	}
}

#PUT
PUT http://localhost:8000/flights/(?id)
content-type: application/json
{
	"AirplaneModel": "sadasdusho",
	"AirplaneNumber": "2213",
	"Price": 32432,
	"Depart": {
		"Country": "peru",
		"City": "Lima",
		"TD": "12:20",
		"TA": "22:20"
	},
	"Destin": {
		"Country": "Colombia",
		"City": "Cali",
		"TD": "11:20",
		"TA": "21:20"
	},
	"seats": [
		{
			"UserID": "ABC",
			"Number": "2A",
			"Type": "Full"
		},
		{
			"UserID": "BBB",
			"Number": "32A",
			"Type": "Full"
		}
	]
}

#Delete
DELETE http://localhost:8000/flights/(?id)

###Bookings
#GET
GET http://localhost:8000/bookings

#POST
POST http://localhost:8000/bookings
content-type: application/json
{
    "userid": "(?id)",
    "flightid": "(?id)",
    "personalseat": {
        "UserID": "(?id)",
        "Number": "33A",
        "Type": "full"
    }
}

#PUT
PUT http://localhost:8000/bookings/(?id)
content-type: application/json
{
	TAMAL, PARLAR CON PRRULISES
}

#Delete
DELETE http://localhost:8000/bookings/(?id)
