// en construccion..., con extension Rest Client
//para Flights
{
	"AirplaneModel": "sadasdusho",
	"AirplaneNumber": "2213",
	"Price": 32432,
	"Depart": {
		"Country": "peru",
		"City": "Lima",
		"TD": "12:20",
		"TA": "22:20"
	},
	"Destin": {
		"Country": "Colombia",
		"City": "Cali",
		"TD": "11:20",
		"TA": "21:20"
	}
}
//Flights con 2 asientos
{
	"AirplaneModel": "sadasdusho",
	"AirplaneNumber": "2213",
	"Price": 32432,
	"Depart": {
		"Country": "peru",
		"City": "Lima",
		"TD": "12:20",
		"TA": "22:20"
	},
	"Destin": {
		"Country": "Colombia",
		"City": "Cali",
		"TD": "11:20",
		"TA": "21:20"
	},
	"seats": [
		{
			"UserID": "ABC",
			"Number": "2A",
			"Type": "Full"
		},
		{
			"UserID": "BBB",
			"Number": "32A",
			"Type": "Full"
		}
	]
}

//Users
{
    "firstname": "ffffcsdsd",
    "lastname": "xtuki",
    "passporttype": "DNI",
    "passportnumber": "434",
    "email": "david@gmail.com",
    "password": "iksdi",
    "personalcard": {
        "card": "Visa",
        "cardnumber": "2323",
        "csc": "2232323",
        "total": 2332,
        "expirationdate": "23/21/1923"
    }
}

//Bookings
{
    "userid": "59cf2dc2f36d286c005cbf61",
    "flightid": "59cc07ed6422e813bfcebb70",
    "personalseat": {
        "UserID": "59cf2dc2f36d286c005cbf61",
        "Number": "33A",
        "Type": "full"
    }
}